<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="TasksTab.aspx.cs" Inherits="WebApplication1.TasksTab" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <style type="text/css">
        .div2 {
            position: absolute;
            left: 283px;
            top: 328px;
            width: 85%;
            height: 41px;
        }
    </style>

    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-2" style="width: 15%">
                <ul class="nav nav-pills nav-stacked">
                    <li class="active"><a href="/Tasks/TasksTab.aspx">Tasks/Activity Log</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Tasks<span class="caret"></span></a>
                        <ul class="dropdown-menu" style="color: black">
                            <li><a href="/Tasks/AssignTask.aspx">Assign a Task</a></li>
                        </ul>
                    </li>
                    <li><a href="/Tasks/timelinePage.aspx">Activity Log Timeline</a></li>
                </ul>
            </div>
        </div>
    </div>


        <div class="div2">
            <hr style="height: -12px" />
            <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
            <asp:UpdatePanel ID="UpdatePanel1" UpdateMode="Conditional" runat="server">
                <ContentTemplate>
                    <asp:DropDownList ID="ddl_clientName" runat="server" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" Height="24px" Width="115px" AppendDataBoundItems="True" AutoPostBack="True">
                        <asp:ListItem Selected="True" Value="All Cases">All Cases</asp:ListItem>
                    </asp:DropDownList>
                    &nbsp;&nbsp;&nbsp;
                    <asp:DropDownList ID="ddl_caseNum" runat="server" Width="115px" Height="24px">
                        <asp:ListItem Value="All Cases">All Cases</asp:ListItem>
                    </asp:DropDownList>
                    &nbsp;&nbsp;&nbsp;
                    <asp:Button ID="sortButton" runat="server" Height="22px" OnClick="Sort_Click" Style="margin-top: 0px" Text="Sort Cases" PostBackUrl="~/Tasks/TasksTab.aspx" CausesValidation="False" />
                </ContentTemplate>
            </asp:UpdatePanel>

            <asp:UpdatePanel ID="UpdatePanel2" UpdateMode="Always" runat="server">
                <ContentTemplate>     
                    <div>
                        <hr style="height: -12px" />
                        <asp:GridView ID="GridView1" runat="server" cssClass="table table-striped" DataKeyNames="TaskNum" EmptyDataText="No Tasks Available"
                            OnRowDataBound="GridView1_RowDataBound" CellPadding="4" ForeColor="Black" AllowSorting="True"
                            OnRowCommand="GridView1_RowCommand" BackColor="#CCCCCC" BorderColor="#999999" OnRowDeleting="GridView1_RowDeleting"
                            BorderStyle="Solid" BorderWidth="3px" Style="margin-left: 0px" AutoGenerateColumns="False" EnableSortingAndPagingCallbacks="True" AutoGenerateDeleteButton="True" CellSpacing="5">
                            <Columns>
                                <asp:BoundField DataField="TaskNum" HeaderText="Task #" ReadOnly="True" />
                                <asp:BoundField DataField="ClientName" HeaderText="Client Name" SortExpression="ClientName" />
                                <asp:BoundField DataField="CaseNum" HeaderText="Case #" SortExpression="CaseNum" />
                                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                                <asp:BoundField DataField="Task" HeaderText="Task" SortExpression="Task" />
                                <asp:BoundField DataField="Date_Assigned" HeaderText="Date Assigned" SortExpression="Date_Assigned" />
                                <asp:BoundField DataField="Date_Completed" HeaderText="Date Completed" SortExpression="Date_Completed" />
                                <asp:TemplateField HeaderText="Status" SortExpression="Status">
                                    <ItemTemplate>
                                        <asp:DropDownList ID="ddl_status" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddl_selected_SelectedIndexChanged">
                                            <asp:ListItem>Assigned</asp:ListItem>
                                            <asp:ListItem>Pending</asp:ListItem>
                                            <asp:ListItem>Completed</asp:ListItem>
                                        </asp:DropDownList>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:ButtonField ButtonType="Button" CommandName="addNote" Text="Add Note" />
                                <asp:TemplateField HeaderText="Notes">
                                    <ItemTemplate>
                                        <img alt="" style="cursor: pointer" src="../Images/plus.png" />
                                        <asp:Panel ID="pnlNotes" runat="server" Style="display: none">
                                            <asp:GridView ID="gvNotes" runat="server" AutoGenerateColumns="false" CssClass="ChildGrid" EmptyDataText="No notes have been added.">
                                                <Columns>
                                                    <asp:BoundField ItemStyle-Width="300px" DataField="Note" HeaderText="Note" />
                                                    <asp:BoundField ItemStyle-Width="200px" DataField="Timestamp" HeaderText="Date" />
                                                </Columns>
                                            </asp:GridView>
                                        </asp:Panel>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:ButtonField ButtonType="Button" CommandName="Reminder" Text="Send Reminder" />
                            </Columns>
                            <FooterStyle BackColor="#CCCCCC" />
                            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                            <RowStyle BackColor="White" />
                            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#F1F1F1" />
                            <SortedAscendingHeaderStyle BackColor="#808080" />
                            <SortedDescendingCellStyle BackColor="#CAC9C9" />
                            <SortedDescendingHeaderStyle BackColor="#383838" />
                        </asp:GridView>
                        <hr style="height: -12px" />
                    </div>
                </ContentTemplate>
            </asp:UpdatePanel>
        </div>


    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $("[src*=plus]").live("click", function () {
            $(this).closest("tr").after("<tr><td></td><td colspan = '999'>" + $(this).next().html() + "</td></tr>")
            $(this).attr("src", "../Images/minus.png");
        });
        $("[src*=minus]").live("click", function () {
            $(this).attr("src", "../Images/plus.png");
            $(this).closest("tr").next().remove();
        });
    </script>

    <script type="text/javascript">
        $(".acknowledge").on("mouseover", function (rowIndex) {
            var gv = document.getElementById("GridView1");
            var rowElement = gv.rows[rowIndex];
            rowElement.style.backgroundColor = "#a8e4b6";
            rowElement.cells[5] = 1;
        });
    </script>

</asp:Content>

